# Generated by Django 4.0 on 2022-02-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherForecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherviewer',
            name='weatherAddressCity',
            field=models.TextField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='weatherviewer',
            name='weatherAddressCountry',
            field=models.TextField(blank=True, max_length=127, null=True),
        ),
    ]
