# Generated by Django 4.0 on 2022-01-28 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('mainPets', '0006_remove_like_likedperson_remove_like_likedpost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likedPerson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Лайкнувший', to='authentication.customuser')),
                ('likedPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Пост', to='mainPets.post')),
            ],
            options={
                'verbose_name_plural': 'Likes',
            },
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followedPerson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Пользователь', to='authentication.customuser')),
                ('followerPerson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Подписавшийся', to='authentication.customuser')),
            ],
            options={
                'verbose_name_plural': 'Followers',
            },
        ),
    ]
