# Generated by Django 4.0 on 2022-01-29 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('mainPets', '0006_remove_like_likedperson_remove_like_likedpost_and_more'),
        ('relation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='LikePost',
        ),
        migrations.AlterModelOptions(
            name='likepost',
            options={'verbose_name_plural': 'LikePosts'},
        ),
        migrations.CreateModel(
            name='LikeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likedComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Комментарий', to='mainPets.comment')),
                ('likedPerson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Лайкнул', to='authentication.customuser')),
            ],
            options={
                'verbose_name_plural': 'LikeComments',
            },
        ),
    ]
