# Generated by Django 4.0 on 2021-12-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerImage', models.ImageField(upload_to='static/images')),
                ('bannerDescription', models.TextField(max_length=254)),
            ],
        ),
    ]
