# Generated by Django 4.0 on 2021-12-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPets', '0002_alter_banner_bannerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='bannerImage',
            field=models.ImageField(upload_to='images'),
        ),
    ]
