# Generated by Django 4.0 on 2022-01-24 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('mainPets', '0002_remove_postphoto_post_post_postpet_post_postphoto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.TextField(max_length=127)),
                ('commentTimePublished', models.TimeField(auto_now_add=True)),
                ('commentDatePublished', models.DateField(auto_now_add=True)),
                ('commentAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.customuser')),
                ('commentPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPets.post')),
            ],
        ),
    ]
