# Generated by Django 4.0 on 2022-01-28 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('mainPets', '0004_followers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-commentDatePublished']},
        ),
        migrations.AlterModelOptions(
            name='followers',
            options={'verbose_name_plural': 'Followers'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-postDatePublished']},
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likedPerson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Лайкнувший', to='authentication.customuser')),
                ('likedPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Пост', to='mainPets.post')),
            ],
            options={
                'verbose_name_plural': 'Likes',
            },
        ),
    ]
