# Generated by Django 4.0 on 2022-01-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPets', '0005_alter_comment_options_alter_followers_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likedPerson',
        ),
        migrations.RemoveField(
            model_name='like',
            name='likedPost',
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
