# Generated by Django 4.0 on 2021-12-29 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personName', models.CharField(max_length=50)),
                ('personSurname', models.CharField(max_length=50)),
                ('personEmail', models.EmailField(max_length=254, unique=True)),
                ('personPassword', models.TextField()),
                ('personLink', models.CharField(blank=True, max_length=31, unique=True)),
                ('personBio', models.TextField(blank=True, max_length=500, null=True)),
                ('personAvatar', models.ImageField(blank=True, null=True, upload_to='upload_to="images"', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])])),
            ],
        ),
    ]
